require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InJobTrainCatalogsController do

  # This should return the minimal set of attributes required to create a valid
  # InJobTrainCatalog. As you add validations to InJobTrainCatalog, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InJobTrainCatalogsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all in_job_train_catalogs as @in_job_train_catalogs" do
      in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
      get :index, {}, valid_session
      assigns(:in_job_train_catalogs).should eq([in_job_train_catalog])
    end
  end

  describe "GET show" do
    it "assigns the requested in_job_train_catalog as @in_job_train_catalog" do
      in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
      get :show, {:id => in_job_train_catalog.to_param}, valid_session
      assigns(:in_job_train_catalog).should eq(in_job_train_catalog)
    end
  end

  describe "GET new" do
    it "assigns a new in_job_train_catalog as @in_job_train_catalog" do
      get :new, {}, valid_session
      assigns(:in_job_train_catalog).should be_a_new(InJobTrainCatalog)
    end
  end

  describe "GET edit" do
    it "assigns the requested in_job_train_catalog as @in_job_train_catalog" do
      in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
      get :edit, {:id => in_job_train_catalog.to_param}, valid_session
      assigns(:in_job_train_catalog).should eq(in_job_train_catalog)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InJobTrainCatalog" do
        expect {
          post :create, {:in_job_train_catalog => valid_attributes}, valid_session
        }.to change(InJobTrainCatalog, :count).by(1)
      end

      it "assigns a newly created in_job_train_catalog as @in_job_train_catalog" do
        post :create, {:in_job_train_catalog => valid_attributes}, valid_session
        assigns(:in_job_train_catalog).should be_a(InJobTrainCatalog)
        assigns(:in_job_train_catalog).should be_persisted
      end

      it "redirects to the created in_job_train_catalog" do
        post :create, {:in_job_train_catalog => valid_attributes}, valid_session
        response.should redirect_to(InJobTrainCatalog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved in_job_train_catalog as @in_job_train_catalog" do
        # Trigger the behavior that occurs when invalid params are submitted
        InJobTrainCatalog.any_instance.stub(:save).and_return(false)
        post :create, {:in_job_train_catalog => {}}, valid_session
        assigns(:in_job_train_catalog).should be_a_new(InJobTrainCatalog)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InJobTrainCatalog.any_instance.stub(:save).and_return(false)
        post :create, {:in_job_train_catalog => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested in_job_train_catalog" do
        in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
        # Assuming there are no other in_job_train_catalogs in the database, this
        # specifies that the InJobTrainCatalog created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InJobTrainCatalog.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => in_job_train_catalog.to_param, :in_job_train_catalog => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested in_job_train_catalog as @in_job_train_catalog" do
        in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
        put :update, {:id => in_job_train_catalog.to_param, :in_job_train_catalog => valid_attributes}, valid_session
        assigns(:in_job_train_catalog).should eq(in_job_train_catalog)
      end

      it "redirects to the in_job_train_catalog" do
        in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
        put :update, {:id => in_job_train_catalog.to_param, :in_job_train_catalog => valid_attributes}, valid_session
        response.should redirect_to(in_job_train_catalog)
      end
    end

    describe "with invalid params" do
      it "assigns the in_job_train_catalog as @in_job_train_catalog" do
        in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InJobTrainCatalog.any_instance.stub(:save).and_return(false)
        put :update, {:id => in_job_train_catalog.to_param, :in_job_train_catalog => {}}, valid_session
        assigns(:in_job_train_catalog).should eq(in_job_train_catalog)
      end

      it "re-renders the 'edit' template" do
        in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InJobTrainCatalog.any_instance.stub(:save).and_return(false)
        put :update, {:id => in_job_train_catalog.to_param, :in_job_train_catalog => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested in_job_train_catalog" do
      in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
      expect {
        delete :destroy, {:id => in_job_train_catalog.to_param}, valid_session
      }.to change(InJobTrainCatalog, :count).by(-1)
    end

    it "redirects to the in_job_train_catalogs list" do
      in_job_train_catalog = InJobTrainCatalog.create! valid_attributes
      delete :destroy, {:id => in_job_train_catalog.to_param}, valid_session
      response.should redirect_to(in_job_train_catalogs_url)
    end
  end

end
