require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrainCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # TrainCategory. As you add validations to TrainCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TrainCategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all train_categories as @train_categories" do
      train_category = TrainCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:train_categories).should eq([train_category])
    end
  end

  describe "GET show" do
    it "assigns the requested train_category as @train_category" do
      train_category = TrainCategory.create! valid_attributes
      get :show, {:id => train_category.to_param}, valid_session
      assigns(:train_category).should eq(train_category)
    end
  end

  describe "GET new" do
    it "assigns a new train_category as @train_category" do
      get :new, {}, valid_session
      assigns(:train_category).should be_a_new(TrainCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested train_category as @train_category" do
      train_category = TrainCategory.create! valid_attributes
      get :edit, {:id => train_category.to_param}, valid_session
      assigns(:train_category).should eq(train_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TrainCategory" do
        expect {
          post :create, {:train_category => valid_attributes}, valid_session
        }.to change(TrainCategory, :count).by(1)
      end

      it "assigns a newly created train_category as @train_category" do
        post :create, {:train_category => valid_attributes}, valid_session
        assigns(:train_category).should be_a(TrainCategory)
        assigns(:train_category).should be_persisted
      end

      it "redirects to the created train_category" do
        post :create, {:train_category => valid_attributes}, valid_session
        response.should redirect_to(TrainCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved train_category as @train_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        TrainCategory.any_instance.stub(:save).and_return(false)
        post :create, {:train_category => {}}, valid_session
        assigns(:train_category).should be_a_new(TrainCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TrainCategory.any_instance.stub(:save).and_return(false)
        post :create, {:train_category => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested train_category" do
        train_category = TrainCategory.create! valid_attributes
        # Assuming there are no other train_categories in the database, this
        # specifies that the TrainCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TrainCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => train_category.to_param, :train_category => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested train_category as @train_category" do
        train_category = TrainCategory.create! valid_attributes
        put :update, {:id => train_category.to_param, :train_category => valid_attributes}, valid_session
        assigns(:train_category).should eq(train_category)
      end

      it "redirects to the train_category" do
        train_category = TrainCategory.create! valid_attributes
        put :update, {:id => train_category.to_param, :train_category => valid_attributes}, valid_session
        response.should redirect_to(train_category)
      end
    end

    describe "with invalid params" do
      it "assigns the train_category as @train_category" do
        train_category = TrainCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TrainCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => train_category.to_param, :train_category => {}}, valid_session
        assigns(:train_category).should eq(train_category)
      end

      it "re-renders the 'edit' template" do
        train_category = TrainCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TrainCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => train_category.to_param, :train_category => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested train_category" do
      train_category = TrainCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => train_category.to_param}, valid_session
      }.to change(TrainCategory, :count).by(-1)
    end

    it "redirects to the train_categories list" do
      train_category = TrainCategory.create! valid_attributes
      delete :destroy, {:id => train_category.to_param}, valid_session
      response.should redirect_to(train_categories_url)
    end
  end

end
